# lesson-db-module/charts/django-app/values.yaml

image:
  repository: 
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

config:
    POSTGRES_HOST: postgress
    POSTGRES_PORT: 5432
    POSTGRES_USER: django_user
    POSTGRES_DB: django_db
    POSTGRES_PASSWORD: ""

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  