# lesson-db-module/charts/django-app/values.yaml

image:
  repository: 768405431530.dkr.ecr.eu-west-1.amazonaws.com/lesson-db-module
  tag: v1.0.7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

config:
    POSTGRES_HOST: db
    POSTGRES_PORT: "5432"
    POSTGRES_USER: django_user
    POSTGRES_DB: django_db
    POSTGRES_PASSWORD: pass9764gd

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  