# lesson-db-module/charts/django-app/values.yaml

image:
  repository: 
  tag: v1.0.5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

config:
    POSTGRES_HOST: "${module.rds.aurora_endpoints}"
    POSTGRES_PORT: 5432
    POSTGRES_USER: django_user
    POSTGRES_DB: "${module.rds.db_name}"
    POSTGRES_PASSWORD: "${module.rds.password}"

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  