# final/docker/nginx/default.conf
# Визначаємо серверний блок (server block), який відповідає за обробку HTTP-запитів
server {
    # Вказуємо порт, на якому Nginx слухатиме запити
    listen 80;
    # Налаштовуємо обробку запитів для кореневого маршруту "/"
    location / {        
        proxy_pass http://django-app-django:8081;        
        proxy_set_header Host $host;        
        proxy_set_header X-Real-IP $remote_addr;        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
