# lesson-db-module/modules/argo_cd/charts/values.yaml

applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/petroDavydov/my-microservice-project.git
      path: lesson-8-9/charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# repositories:
#   - name: example-app
#     url:  https://github.com/petroDavydov/my-microservice-project.git
#     # username: petroDavydov
#     # password: YOUR_PASS

# repoConfig:
#   insecure: "true"
#   enableLfs: "true"
