# final/charts/django-app/values.yaml

image:
  repository: ""
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8081

config:
    POSTGRES_HOST: ""
    POSTGRES_PORT: ""
    POSTGRES_USER: ""
    POSTGRES_DB: ""
    POSTGRES_PASSWORD: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  