# final/charts/django-app/values.yaml

image:
  repository: 768405431530.dkr.ecr.eu-west-1.amazonaws.com/final
  tag: v1.0.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8081

config:
    POSTGRES_HOST: ""
    POSTGRES_PORT: ""
    POSTGRES_USER: ""
    POSTGRES_DB: ""
    POSTGRES_PASSWORD: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  