# lesson-7/charts/values.yaml

image:
  repository: arturshopengauergik/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
    POSTGRES_HOST: db 
    POSTGRES_PORT: 5432
    POSTGRES_USER: django_user
    POSTGRES_DB: django_db
    POSTGRES_PASSWORD: "123456789"

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70